diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/StudySoftwares/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Baidou
user.email=1424089348@qq.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=store
http.proxy=http://127.0.0.1:7897
core.autocrlf=true
core.compression=0
https.proxy=http://127.0.0.1:7897
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
branch.main.gk-last-accessed=2026-01-21T08:57:37.863Z
branch.main.gk-last-modified=2026-01-21T08:52:05.164Z
remote.origin.url=https://github.com/Baidou2Star/myChat.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
